Class = require("Libs/class")
Timer = require("Libs.timer")
Anim8 = require("Libs.anim8")

require("Src.Assets")
require("Src.Constants")
require("Src.Utils")

require("Src.Element")
require("Src.Board")
require("Src.CollisionBox")
require("Src.VisualEffects.ScanLine")
require("Src.TopScreen")
require("Src.Player")
require("Src.Enemy")
